SSLCipherSuite HIGH:!aNULL:!MD5:!RC4:!3DES:!CAMELLIA
SSLProxyCipherSuite HIGH:!aNULL:!MD5:!RC4:!3DES:!CAMELLIA
SSLHonorCipherOrder on

SSLProtocol TLSv1.2 TLSv1.3
SSLProxyProtocol TLSv1.2 TLSv1.3

SSLSessionCache "shmcb:${APACHE_RUN_DIR}/ssl_scache(512000)"
SSLSessionCacheTimeout 300

<VirtualHost _default_:443>
    ServerName localhost
    DocumentRoot ${APACHE_DOCUMENT_ROOT}

    SSLEngine on
    SSLCertificateFile /etc/apache2/ssl/certificate.crt
    SSLCertificateKeyFile /etc/apache2/ssl/private.key

    <Directory ${APACHE_DOCUMENT_ROOT}>
        Options Indexes FollowSymLinks Includes ExecCGI
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/ssl-error.log
    CustomLog ${APACHE_LOG_DIR}/ssl-access.log combined
</VirtualHost>

<VirtualHost _default_:443>
    UseCanonicalName Off
    ServerAlias *.test

    SSLEngine on
    SSLCertificateFile /etc/apache2/ssl/certificate.crt
    SSLCertificateKeyFile /etc/apache2/ssl/private.key

    VirtualDocumentRoot ${APACHE_DOCUMENT_ROOT}/%-2

    <Directory ${APACHE_DOCUMENT_ROOT}>
        Options Indexes FollowSymLinks Includes ExecCGI
        AllowOverride All
        Require all granted
    </Directory>

    <DirectoryMatch "^${APACHE_DOCUMENT_ROOT}/([^/]+)">
        AllowOverride All
        Require all granted
    </DirectoryMatch>

    ErrorLog ${APACHE_LOG_DIR}/ssl-error.log
    CustomLog ${APACHE_LOG_DIR}/ssl-access.log combined
</VirtualHost>
